### ISSUE TITLE
Broken sub links

### ISSUE THREAD

**Issue by carduz** [hypermedia2016/design#3]
![schermata del 2016-05-03 17-08-41](https://cloud.githubusercontent.com/assets/10631614/14987942/f3fb1d8a-1151-11e6-9540-e04fa9ecdffa.png)

**Comment by carduz** [comment]
the group -> for investors

**Comment by DeadManPoe** [comment]
Sublinks are not meant to work, their function is to facilitate the user experience: if they are pressed the page will scroll down to the correspondant section, this behavior cannot be modelled in pencil and it is not necessary to do so
