### ISSUE TITLE
Smart life not underlined, chain links not active

### ISSUE THREAD

**Issue by carduz** [hypermedia2016/design#4]
![schermata del 2016-05-03 17-09-50](https://cloud.githubusercontent.com/assets/10631614/14987990/1fcdf3ec-1152-11e6-92b2-5c4d31eee707.png)

**Comment by carduz** [comment]
all links point to devices' pages

**Comment by DeadManPoe** [comment]
The smartband is a device and therefore devices is underlined. Not every part of the the breadcrumb should be active i will place a off mark to those part that are not active while they should be, however in the document there exist a breadcrumb with all the links functional and it will be an example
