### ISSUE TITLE
Smart life sub links don't work and there is no link to home page of smartlife services

### ISSUE THREAD

**Issue by carduz** [hypermedia2016/design#5]
![schermata del 2016-05-03 17-13-25](https://cloud.githubusercontent.com/assets/10631614/14988043/6d4e4c34-1152-11e6-844e-82dccbc1c730.png)

**Comment by DeadManPoe** [comment]
Fixed see other issue for sublink, subscribe btns are not meant to be functonal i will put an off mark on them
