### ISSUE TITLE
Apple doens't work

### ISSUE THREAD

**Issue by carduz** [hypermedia2016/design#7]
![schermata del 2016-05-03 17-19-06](https://cloud.githubusercontent.com/assets/10631614/14988211/31f7e978-1153-11e6-8d41-eefd73c4f8f9.png)

**Comment by carduz** [comment]
other analogous problems in other sections

**Comment by DeadManPoe** [comment]
Fixed, apple's link for the smartwatch will not work since only for tablets i made the section
